/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package chessengine;

import javafx.application.Application;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.stage.Stage;

import java.io.IOException;

public class App extends Application {

    private final String startUrl = "/FxmlFiles/MainScreen.fxml";
    private Scene startScene;
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args){
        launch(args);
    }

    @Override
    public void start(Stage primaryStage) throws Exception {
        try {
            FXMLLoader fxmlLoader = new FXMLLoader(App.class.getResource(startUrl));
            fxmlLoader.setControllerFactory(c -> new mainScreenController()); // Set controller factory
            Parent startRoot = fxmlLoader.load();
            startScene = new Scene(startRoot);


        } catch (IOException e) {
            e.printStackTrace();
        }
        primaryStage.setScene(startScene);
        primaryStage.show();
    }
}
